// <auto-generated />
using System;
using CartaNoAdeudoApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CartaNoAdeudoApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917212128_AddControlFolioAndFrase")]
    partial class AddControlFolioAndFrase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Bitacora.Carta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<Guid>("IdDato")
                        .HasColumnType("uuid")
                        .HasColumnName("id_dato");

                    b.HasKey("Id");

                    b.HasIndex("IdDato");

                    b.ToTable("carta", "bit");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Bitacora.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.ToTable("config", "bit");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.Archivos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Carta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("carta");

                    b.Property<Guid>("IdDato")
                        .HasColumnType("uuid")
                        .HasColumnName("id_dato");

                    b.HasKey("Id");

                    b.HasIndex("IdDato")
                        .IsUnique();

                    b.ToTable("archivos", "carta");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.Datos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_dato");

                    b.Property<string>("Alcoholes")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("alcoholes");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estatus");

                    b.Property<DateTimeOffset?>("FechaFirmado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_firmado");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Folio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("folio");

                    b.Property<int>("IdTipoCarta")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_carta");

                    b.Property<DateOnly>("InicioVigencia")
                        .HasColumnType("date")
                        .HasColumnName("inicio_vigencia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("RO")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("ro");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("rfc");

                    b.Property<bool>("Vencida")
                        .HasColumnType("boolean")
                        .HasColumnName("vencida");

                    b.Property<DateOnly>("Vencimiento")
                        .HasColumnType("date")
                        .HasColumnName("vencimiento");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoCarta");

                    b.HasIndex("RO", "IdTipoCarta");

                    b.ToTable("datos", "carta");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.Firmas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_firma");

                    b.Property<string>("Certificado")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("certificado");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("FingerPrint")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("finger_print");

                    b.Property<string>("Firma")
                        .HasColumnType("text")
                        .HasColumnName("firma");

                    b.Property<string>("HexSerie")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hex_serie");

                    b.Property<Guid>("IdDato")
                        .HasColumnType("uuid")
                        .HasColumnName("id_dato");

                    b.Property<string>("Identificador")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("identificador");

                    b.HasKey("Id");

                    b.HasIndex("IdDato");

                    b.ToTable("firmas", "carta");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.FolioConsecutivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTimeOffset>("FechaCreo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creo");

                    b.Property<DateTimeOffset?>("FechaEdito")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_edito");

                    b.Property<Guid?>("IdCreo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_creo");

                    b.Property<Guid?>("IdEdito")
                        .HasColumnType("uuid")
                        .HasColumnName("id_edito");

                    b.Property<string>("TipoCarta")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tipo_carta");

                    b.Property<int>("UltimoFolio")
                        .HasColumnType("integer")
                        .HasColumnName("ultimo_folio");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TipoCarta")
                        .IsUnique();

                    b.ToTable("folios_consecutivos", "carta");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.Tareas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTimeOffset>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<Guid>("IdDato")
                        .HasColumnType("uuid")
                        .HasColumnName("id_dato");

                    b.Property<Guid>("IdEstado")
                        .HasColumnType("uuid")
                        .HasColumnName("id_estado");

                    b.Property<string>("MensajeError")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mensaje_error");

                    b.Property<string>("Nota")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nota");

                    b.HasKey("Id");

                    b.HasIndex("IdDato");

                    b.HasIndex("IdEstado");

                    b.ToTable("tareas", "carta");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.TiposCartas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_carta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("tipos_cartas", "carta");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Catalogos.Estado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("estado", "cat");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Catalogos.EstadoTarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("estado_tarea", "cat");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Catalogos.Firmante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Certificado")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("certificado");

                    b.Property<string>("Contrasena")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contrasena");

                    b.Property<string>("EstatusCertificado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estatus_certificado");

                    b.Property<DateTimeOffset>("FechaCreo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creo");

                    b.Property<DateTimeOffset?>("FechaEdito")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_edito");

                    b.Property<DateOnly>("FechaFinAutorizada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin_autorizada");

                    b.Property<DateOnly>("FechaFinCertificado")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin_certificado");

                    b.Property<DateOnly>("FechaInicioAutorizada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio_autorizada");

                    b.Property<DateOnly>("FechaInicioCertificado")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio_certificado");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("genero");

                    b.Property<Guid?>("IdCreo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_creo");

                    b.Property<Guid?>("IdEdito")
                        .HasColumnType("uuid")
                        .HasColumnName("id_edito");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pfx")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pfx");

                    b.Property<string>("Puesto")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("puesto");

                    b.HasKey("Id");

                    b.HasIndex("Activo", "FechaInicioAutorizada", "FechaFinAutorizada");

                    b.ToTable("firmante", "cat");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Catalogos.Frase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<DateTimeOffset>("FechaCreo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creo");

                    b.Property<DateTimeOffset?>("FechaEdito")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_edito");

                    b.Property<DateOnly>("FechaFinAutorizada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin_autorizada");

                    b.Property<DateOnly>("FechaInicioAutorizada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio_autorizada");

                    b.Property<Guid?>("IdCreo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_creo");

                    b.Property<Guid?>("IdEdito")
                        .HasColumnType("uuid")
                        .HasColumnName("id_edito");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("frase");

                    b.HasKey("Id");

                    b.HasIndex("Anio");

                    b.ToTable("frases", "cat");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Catalogos.Layout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("archivo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTimeOffset>("FechaCreo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creo");

                    b.Property<DateTimeOffset?>("FechaEdito")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_edito");

                    b.Property<DateOnly>("FechaFinAutorizada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin_autorizada");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<DateOnly>("FechaInicioAutorizada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio_autorizada");

                    b.Property<Guid?>("IdCreo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_creo");

                    b.Property<Guid?>("IdEdito")
                        .HasColumnType("uuid")
                        .HasColumnName("id_edito");

                    b.HasKey("Id");

                    b.HasIndex("Activo", "FechaInicioAutorizada", "FechaFinAutorizada");

                    b.ToTable("layout", "cat");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Sistema.Configuracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("descripcion");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("configuracion", "sist");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Sistema.ControlFolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<int>("UltimoFolio")
                        .HasColumnType("integer")
                        .HasColumnName("ultimo_folio");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Anio")
                        .IsUnique();

                    b.ToTable("control_folios", "sist");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Bitacora.Carta", b =>
                {
                    b.HasOne("CartaNoAdeudoApi.Core.Entities.Cartas.Datos", "Dato")
                        .WithMany("Bitacora")
                        .HasForeignKey("IdDato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dato");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.Archivos", b =>
                {
                    b.HasOne("CartaNoAdeudoApi.Core.Entities.Cartas.Datos", "Dato")
                        .WithOne("Archivo")
                        .HasForeignKey("CartaNoAdeudoApi.Core.Entities.Cartas.Archivos", "IdDato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dato");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.Datos", b =>
                {
                    b.HasOne("CartaNoAdeudoApi.Core.Entities.Cartas.TiposCartas", "TipoCarta")
                        .WithMany("Datos")
                        .HasForeignKey("IdTipoCarta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCarta");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.Firmas", b =>
                {
                    b.HasOne("CartaNoAdeudoApi.Core.Entities.Cartas.Datos", "Dato")
                        .WithMany("Firmas")
                        .HasForeignKey("IdDato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dato");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.Tareas", b =>
                {
                    b.HasOne("CartaNoAdeudoApi.Core.Entities.Cartas.Datos", "Dato")
                        .WithMany("Tareas")
                        .HasForeignKey("IdDato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartaNoAdeudoApi.Core.Entities.Catalogos.EstadoTarea", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dato");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.Datos", b =>
                {
                    b.Navigation("Archivo");

                    b.Navigation("Bitacora");

                    b.Navigation("Firmas");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("CartaNoAdeudoApi.Core.Entities.Cartas.TiposCartas", b =>
                {
                    b.Navigation("Datos");
                });
#pragma warning restore 612, 618
        }
    }
}
